# Generated by Django 4.2.16 on 2026-06-04 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='budget_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='budget_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='preferred_style',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='requirements',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='sample_references',
            field=models.TextField(blank=True, help_text='URLs or descriptions of reference works'),
        ),
        migrations.AddField(
            model_name='project',
            name='special_constraints',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target_audience',
            field=models.TextField(blank=True),
        ),
    ]
