# Generated by Django 4.2.16 on 2026-04-22 06:07

import apps.files.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=apps.files.models.upload_to, validators=[apps.files.models.validate_file])),
                ('original_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('project_attachment', 'Project Attachment'), ('project_request', 'Project Request'), ('deliverable', 'Deliverable'), ('revision', 'Revision'), ('ticket', 'Ticket'), ('freelancer_doc', 'Freelancer Document'), ('sample_reference', 'Sample Reference'), ('final_output', 'Final Output'), ('avatar', 'Avatar'), ('general', 'General')], default='general', max_length=30)),
                ('content_type', models.CharField(max_length=100)),
                ('size', models.PositiveBigIntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='projects.project')),
                ('project_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='projects.projectrequest')),
                ('revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='projects.projectrevision')),
            ],
            options={
                'db_table': 'uploaded_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
