# Generated by Django 4.2.16 on 2026-04-22 06:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('project_assigned', 'Project Assigned'), ('project_status_updated', 'Project Status Updated'), ('project_request_reviewed', 'Project Request Reviewed'), ('revision_requested', 'Revision Requested'), ('revision_reviewed', 'Revision Reviewed'), ('delivery_approved', 'Delivery Approved'), ('ticket_replied', 'Ticket Replied'), ('new_ticket', 'New Ticket'), ('payment_status', 'Payment Status Changed'), ('wallet_adjusted', 'Wallet Adjusted'), ('file_uploaded', 'File Uploaded'), ('new_project_request', 'New Project Request'), ('general', 'General')], default='general', max_length=40)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('data', models.JSONField(default=dict)),
                ('is_read', models.BooleanField(default=False)),
                ('related_object_id', models.CharField(blank=True, max_length=100)),
                ('related_object_type', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
